### ISSUE TITLE
Add domain aliases (www.) support for s3_hosting module

### ISSUE THREAD

**Issue by bmonkman** [commitdev/terraform-aws-zero#7]
We should be able to provide a list of domain aliases to s3_hosting to allow us to specify hostnames in the case where we want to have a single bucket with multiple names. For example, commit.dev and www.commit.dev

**Comment by pthieu** [comment]
@bmonkman you can have a CF distribution accept two domains and point to the same bucket. Pros and cons here, we can have granularity and absolute segregation between configurations, but we can also simply it, especially of it's `www.` vs `@`.

Let me know what the best practice is.

**Comment by pthieu** [comment]
@bmonkman to clarify, this is `CF (www) -> S3 -> redirect -> CF (@) -> S3`?

**Comment by bmonkman** [comment]
From a client browser PoV it's just a 301 redirect from www.domain.com to domain.com and behind the scenes it will be all cached in cloudfront.
